title: sncouncil
email: skuldnorniern@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Council for every programmer that have any interest in Skuld Norniern's Project's
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://skuldnorniern.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SkuldNorniern
github_username:  SkuldNorniern


header_transparent: true
lang: "en"

night_mode: "auto"

# defaults:
#   home:
#     heading: "Your awesome heading"
#     subheading: "Your awesome subheading"
#     banner: "./assets/images/banners/home.jpeg"

# Build settings
markdown: kramdown
kmarkdown:
  input: GFM


theme: jekyll-theme-yat
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
