# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'sncouncil'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-NHY61K007Q'

menu: 
  - name: Featured Projects
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/SkuldNorniern
      - name: Twitter
        icon: twitter
        link: https://twitter.com/SkuldNorniern
    
